const express=require('express')
const cors=require('cors')
const configDB=require('./config/database')
const routes=require('./config/routes')
configDB()
const app=express()
app.use(express.json())
app.use(cors())
app.use(routes)
const port=3077
app.listen(port,()=>console.log('server is running at 3077'))
